<a href="https://colab.research.google.com/github/yashasangani/DeepLearning-6th-July/blob/main/forward_propagation_with_hidden_layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0,0,0,1]]).T

In [3]:
x.shape,y.shape

((4, 2), (4, 1))

In [4]:
def sig(z):
  return 1/(1+np.exp(-z))

In [12]:
wh = 2*np.random.random((2,2)) - 1
bh = 2*np.random.random((1,2)) - 1
wo = 2*np.random.random((2,1)) - 1
bo = 2*np.random.random((1,1)) - 1

In [13]:
wh,bh,wo,bo

(array([[-0.30301223,  0.97302322],
        [-0.50207225,  0.25332801]]),
 array([[ 0.46230922, -0.48846544]]),
 array([[0.18249777],
        [0.16689155]]),
 array([[-0.12060418]]))

In [14]:
output0= x
outputhidden = sig(np.dot(output0 , wh) + bh)
outputhidden

array([[0.61356184, 0.38025514],
       [0.49006055, 0.441485  ],
       [0.53974025, 0.61882355],
       [0.41513549, 0.67653336]])

In [15]:
output = sig(np.dot(outputhidden,wo) + bo)
output

array([[0.51370428],
       [0.51062612],
       [0.52028227],
       [0.51700964]])