<a href="https://colab.research.google.com/github/yashasangani/DeepLearning-6th-July/blob/main/Forward_propagation_without_hidden_layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0,0,0,1]]).T

In [6]:
x.shape, y.shape

((4, 2), (4, 1))

In [7]:
def sig(z):
  return 1/(1+np.exp(-z))

In [13]:
weights = 2* np.random.random((2,1))  -1
bias = 2 * np.random.random(1) -1

In [14]:
weights,bias

(array([[-0.27359983],
        [-0.91494049]]),
 array([0.2080523]))

In [15]:
output0 = x
output = sig(np.dot(output0,weights) + bias)
output

array([[0.55182626],
       [0.3302868 ],
       [0.48361898],
       [0.27279496]])